### ISSUE TITLE
커뮤니케이션 채널에 가입하고 사진을 올려주세요

### ISSUE THREAD

**Issue by jongkwang** [iot-labs/farm#1]
안녕하세요.
IoT Labs : farm 의 첫번째 이슈를 생성 합니다.

원활한 커뮤니케이션을 위해
아래 사항을 모두 진행해 주세요.

## 해야 할 것
- Facebook Group 에 가입
  - https://www.facebook.com/groups/IoTLabs
- Slack 가입
  - 초대장 못받으신분 : kim@jongkwang.com 으로 메일 보내주세요. 초대장 보내겠습니다.
  - 컨트리뷰톤 2017 멤버 : 이메일 주소로 초대장을 보내드렸습니다.
- Slack 의 프로필 사진을 본인 사진으로 Update
  - 컨트리뷰톤 2017 멤버
    - 프로필 사진을 가급적 개인 사진으로 변경해주세요. (그래야 얼굴과 이름을 매치 할 수 있어서요)
    - 프로필 사진을 Default 에서 변경하는 것은 강제/필수 사항입니다
    - 하지만, 본인 개인 사진이 꺼려지는 분은 다른 것으로 하셔도 무방합니다.
- https://github.com/iot-labs/farm 프로젝트를 [Watch] 해주세요.
  - 변경사항을 별도로 알려 드리지 않습니다.
  - Watch 로 받아보시는 이메일을 항상 확인 하셔야 합니다.

## 언제까지 해야 하나?
> 컨트리뷰톤 2017 멤버에게만 해당 하는 사항 입니다
- 기한 : 10월 11일 수요일 12시까지 완료해주세요

**Comment by E-nuri** [comment]
<img width="1323" alt="todo" src="https://user-images.githubusercontent.com/20082776/31055378-f2459032-a6fc-11e7-8c5a-a4978a15e567.png">
@jongkwang 반영했습니다.

**Comment by ja-ho** [comment]
확인했습니다!

**Comment by jongkwang** [comment]
@E-nuri 님,

- ***Slack 의 프로필에 사진을 올려 달라는 의미 였습니다.***
  - 이곳 Issue 에 올리는 것이 아니고 ^^;;

> 제가 표현에 혼돈이 있었네요. ㅎㅎㅎ

올리신 것은 놔두고요
다른분들은 올리지 마세요 ^^

**Comment by jongkwang** [comment]
<code>컨트리뷰톤 2017</code> 을 통해 참석하신 분들은
이 이슈가 필수사항 입니다.

아직 진행하지 않으신분은 진행 해주세요 ^^

완료하지 않으신분 명단
- 김정원
- 조대영
- 전태경
- 신기용

> 위 명단은 25일 삭제 하겠습니다. ^^

**Comment by goodGid** [comment]
완료했습니다 !

**Comment by jongkwang** [comment]
수고하셨습니다.
Close 처리 합니다.
