### ISSUE TITLE
장비 구매 : Arduino SDCard Read/Write

### ISSUE THREAD

**Issue by jongkwang** [iot-labs/farm#11]
SDCard Read/Write 할 장비를 선정해 주세요.

* http://eleparts.co.kr 에서 구매하도록 하겠습니다.
* 구매 할 수 있는 URI 를 남겨주세요

**Comment by E-nuri** [comment]
제품 링크 : http://eleparts.co.kr/EPX4XMDW

튜토리얼 링크 : https://kocoafab.cc/tutorial/view/147

**Comment by jongkwang** [comment]
장비 구매가 완료되어 Issue 를  Close 합니다.
