### ISSUE TITLE
장비 구매 : 온/습도 센서

### ISSUE THREAD

**Issue by jongkwang** [iot-labs/farm#12]
온/습도 센서

**우리 프로젝트의 핵심 센서인 만큼
정밀한 장비였으면 더 좋겠습니다.**

* http://eleparts.co.kr 에서 구매하도록 하겠습니다.
* 구매 할 수 있는 URI 를 남겨주세요

**Comment by E-nuri** [comment]
아두이노 스타터킷에 들어 있는 [온습도 센서](http://cfile10.uf.tistory.com/image/2321E13E56EAC72A1E1BCA) 는 측정오차가 큽니다. 다른 부품을 추가 조사해보면 좋겠습니다.

**Comment by jongkwang** [comment]
장비 구매가 완료되어 Issue 를  Close 합니다.
