### ISSUE TITLE
장비 구매 : 광 센서

### ISSUE THREAD

**Issue by jongkwang** [iot-labs/farm#13]
광 센서

* http://eleparts.co.kr 에서 구매하도록 하겠습니다.
* 구매 할 수 있는 URI 를 남겨주세요

**Comment by E-nuri** [comment]
[튜토리얼 링크](https://www.kocoafab.cc/tutorial/view/356)

[빛 감지 센서(cds) 구매 링크](http://eleparts.co.kr/EPX33JYV)

**Comment by jongkwang** [comment]
장비 구매가 완료되어 Issue 를  Close 합니다.
