### ISSUE TITLE
장비 구매 : 토양 수분 센서

### ISSUE THREAD

**Issue by jongkwang** [iot-labs/farm#14]
토양 수분 센서

  1. 참고 : http://codingrun.com/109
  2. 참고 : https://www.kocoafab.cc/tutorial/view/369

----

* http://eleparts.co.kr 에서 구매하도록 하겠습니다.
* 구매 할 수 있는 URI 를 남겨주세요

**Comment by DubleDstudy** [comment]
http://m.hanbit.co.kr/channel/category/category_view.html?cms_code=CMS6824913826

저희 프로젝트랑 연관이 있는거 같아서 올립니다.

**Comment by jongkwang** [comment]
@DubleDstudy 
센서 오차 범위가 있으니,
여러번 측정 후 보정을 하는 군요 ^^

**Comment by jongkwang** [comment]
장비 구매가 완료되어 Issue 를  Close 합니다.
