### ISSUE TITLE
장비 구매 : 기타 장비 (빵판, 전선, 그 외)

### ISSUE THREAD

**Issue by jongkwang** [iot-labs/farm#15]
장비 구매 : 기타 장비 (빵판, 전선, 그 외)

빵판, 전선 이외에 또 뭐가 있어야 할까요?
빵판/전선 URL 도 첨부해 주세요

* http://eleparts.co.kr 에서 구매하도록 하겠습니다.
* 구매 할 수 있는 URI 를 남겨주세요

**Comment by E-nuri** [comment]
부품을 연결해서 쓰려면 납땜 작업도 동반되어야 하는데 혹시 코스랩 사무실에 장비 이용이 가능한지 궁금합니다

**Comment by E-nuri** [comment]
코스랩에 아래 두 권의 책이 있는지 궁금합니다.
여러 미니 프로젝트들이 기록된 책들인데 저희 프로젝트에 도움이 될 것 같습니다.

http://www.yes24.com/24/goods/9167060?scode=032&OzSrank=2

http://www.yes24.com/24/goods/6413291?scode=032&OzSrank=8

**Comment by jongkwang** [comment]
@E-nuri 님,

## 납땜
* 시제품 까지는 빵판으로 하고
* 제품 나오면, 3D Print 케이스와 함께 납땜 작업을 하시지요^^
* 납땜 장비는 구매해 놓도록 하겠습니다. (당장 말고, 조금 있다가 ^^;; )

## 서적
* 위 2권 책은 못봤습니다.
* 필요하면 구매하면 되는데요. 어떻게 할까요?

> 참고로, 비용 지출에 아낌이 없습니다.
> 필요한 것은 모두 구매 하도록 하겠습니다. ^^

**Comment by E-nuri** [comment]
@jongkwang 우선 제작할 기능 구상이 끝나면 다시 의견 나눠보면 좋을 것 같습니다! :)

**Comment by jongkwang** [comment]
장비 구매가 완료되어 Issue 를  Close 합니다.
