### ISSUE TITLE
아두이노 시뮬레이터 이용 건의

### ISSUE THREAD

**Issue by E-nuri** [iot-labs/farm#16]
[아두이노 시뮬레이터](https://circuits.io/lab)를 이용해보는걸 건의합니다.

구글링 할 때 'How to make arduino + @@@@'(예를 들어 How to make arduino thermometer) 형태로 검색하면 참고할 자료들이 무궁무진하게 많이 나옵니다.

하지만 각 포스팅마다 사용한 재료들이 다를테고, 저희가 사용가능한(구매가능한) 부품들이 없을수도 있습니다.

모든 부품을 구매하는것은 비용, 시간이 많이 소모되므로 위의 시뮬레이터를 이용해서 미리 프로토타입을 만들어보고 부품 구매하는건 어떨까요?

[시뮬레이터 작동 샘플영상](https://www.youtube.com/watch?v=OCmeyJA5IRk)보시고 의견 코멘트 부탁드립니다.

**Comment by jongkwang** [comment]
@E-nuri 님
오호~ 좋은 말씀 입니다.

한번도 사용 안해봤는데요.
배우는데 난이도는 어떤가요?
(LED 제어 샘플 1개 제작)

저도 한번 해보고 난이도가 어떤지 의견 남기겠습니다.

**Comment by jongkwang** [comment]
README.md 파일에 내용을 추가 했습니다. ^^

![screen shot 2017-10-13 at 6 14 22 pm](https://user-images.githubusercontent.com/897510/31539057-5d93db20-b042-11e7-9ea7-c7713755174f.png)

**Comment by jongkwang** [comment]
제가 30분 헤맨결과

- 이곳이 아니고 : https://circuits.io
- 이곳으로 가야 한다는 것을 알았습니다 : https://www.tinkercad.com/circuits

지금 연습중에 있습니다. ^^
성공하면 공유 할께요

**Comment by jongkwang** [comment]
저의 첫 작품을 공개 합니다. ^^
5분도 안걸리네요. ( 흑흑... 그런데 터졌어요. ㅠㅠ)

우리가 만드려는 부품이 모두 있는지 확인해 보겠습니다. ^^


![fantastic jaiks](https://user-images.githubusercontent.com/897510/31666131-1e6ae94c-b386-11e7-9b6b-b3baf950411d.png)

**Comment by jongkwang** [comment]
IoT Labs : Farm 의 모든 기능을 넣기에는
센서가 부족합니다.

- 있는 센서 : 온도 , 빛 센서
- 없는 센서 : 습도 , 토양온도 , 토양습도

일단 있는 센서 중심으로 먼저 만드는 것도 좋겠습니다.
없는 센서는 실물을 주문 하도록 하겠습니다. 도착하면 같이 하시지요

<img width="1767" alt="screen shot 2017-10-17 at 10 21 26 pm" src="https://user-images.githubusercontent.com/897510/31667184-a0ffaf48-b389-11e7-8300-060ab5b37e84.png">

**Comment by jongkwang** [comment]
이 이슈는 종료 하겠습니다.

센서 제약으로 모든 기능을 만들 수는 없지만,
테스트 용도로 적극 사용 하는 것으로 하시지요
