### ISSUE TITLE
[종광 멘토님께]컨트리뷰톤 현황판에 반영이 안되는 문제

### ISSUE THREAD

**Issue by E-nuri** [iot-labs/farm#17]
https://kosslab-kr.github.io/kosscontributhon2017/index.html

현황판에 저희가 작업한게 반영이 안되고 있습니다.

왜그런가 살펴보니 저희는 iot-labs/farm에서 이슈를 만들고 컨트리뷰팅하고있는데 현황판은 https://github.com/kosslab-kr/farm 여기를 바라보고 있습니다.

저희가 작업한 내용이 현황판에 보이게 하려면 kosslabkr-/farm에서 작업하고 컨트리뷰톤이 끝나면 kosslab-kr 작업 내용을 iot-labs/farm으로 pull 해오는게 좋을듯합니다.

**Comment by jongkwang** [comment]
@E-nuri 
말씀 감사합니다. ^^

## Issue
- 이슈는 Pull 되지 않으니까
- iot-labs/farm 에서 하는 것이 좋겠습니다.

## Code
- Code 는 kosslab-kr/farm 에서 진행할 수 있을텐데요

## 그래서 결론
- 행사를 위해 기록을 kosslabs-kr 에 남기는 것은 아닌 것 같고요
- 행사도 위하고, 프로젝트도 위하는 방법이 있는지 알아 보겠습니다. (17일 화요일저녁 까지)
- 일단은 지금처럼 iot-labs/farm 에서 작업 하시지요 ^^

> 참고로
> 작년에도 똑같이 했었는데요.
> 현황판 활동 내역은 평가에 반영되지는 않았습니다.

문제제기 감사합니다. ^^

**Comment by jongkwang** [comment]
Close 되었던 이슈를 다시 Open 했습니다.
- 커뮤니케이션을 이렇게 한다는 것을, 참조 하시라고 남겨 둡니다.
- 몇일 지나서 Close 시킬께요 ^^

**Comment by jongkwang** [comment]
관련해서 알아 보았습니다.

- 이슈 : IoT Labs 에 올리는 것이 좋겠습니다.
- 코드 : kosslab-kr/farm 에 올리고 Merge 하는 방법이 있으나, 복잡도 상승으로 포기 입니다.

## 결론
- 그냥 https://github.com/iot-labs/farm 이곳에서 활동 하시지요 ^^;;
