### ISSUE TITLE
혹시 git/github이 처음이거나 익숙하지 않은분 계신가요?

### ISSUE THREAD

**Issue by E-nuri** [iot-labs/farm#2]
[github 자료 링크](https://drive.google.com/open?id=0Bzn9675g1wbdMTVfbTZBTXZTaWM)

git/github 사용이 익숙하지 않은 분이 계시면 말씀해주세요.

위의 링크는 예전에 만들었던 자료인데 필요하다면 추석연휴동안 더 보강해서 자료만들고 공유하겠습니다.

**Comment by jongkwang** [comment]
@E-nuri 님,
오호~ 좋은 자료 감사합니다. !!

이 자료는 Wiki 에도 링크 걸어 놓겠습니다. ^^

**Comment by jongkwang** [comment]
https://github.com/iot-labs/farm/wiki

위키에 등록 했습니다.
이슈를 마감합니다.
