### ISSUE TITLE
서버 환경구축

### ISSUE THREAD

**Issue by E-nuri** [iot-labs/farm#24]
회사에서 아는분께 Azure pass를 얻었습니다. 

그래서 이걸로 저렴한 서버(약 월1만원대)를 하나 결제했습니다.

enuri91@gmail.com으로 ssh public key를 보내주시면 서버 접속권한 등록해드리겠습니다.

ssh key 관련해서는 아래 댓글로 달아두겠습니다. 궁금한점은 댓글로 코멘트 달아주세요.

![2017-10-18 1 09 11](https://user-images.githubusercontent.com/20082776/31701545-14abae24-b40c-11e7-9bab-087d8332a8f5.png)

**Comment by E-nuri** [comment]
Mac 사용자 : [참고 링크](https://git-scm.com/book/ko/v1/Git-%EC%84%9C%EB%B2%84-SSH-%EA%B3%B5%EA%B0%9C%ED%82%A4-%EB%A7%8C%EB%93%A4%EA%B8%B0) 

윈도우 사용자 
1. [Git bash](https://git-scm.com/) 를 다운받으셔서 설치합니다.
2. **Git bash**를 실행시키고 Mac 사용자와 같이 키를 생성합니다.
-> [키 생성방법](https://git-scm.com/book/ko/v1/Git-%EC%84%9C%EB%B2%84-SSH-%EA%B3%B5%EA%B0%9C%ED%82%A4-%EB%A7%8C%EB%93%A4%EA%B8%B0)

키를 생성하면 .ssh 경로에 id_rsa와 id_rsa.pub가 생성됩니다.

이 중 id_rsa.pub키를 복사해서 보내주시면 됩니다.

**Comment by jongkwang** [comment]
@E-nuri 님, 감사합니다만, ^^;;;
다른 방법으로 풀어 보겠습니다.

- Azure 는 비용이 어떻게 나올지 모르는 것이라 걱정도 되고요
- 서버는 이쪽에서 준비 하는 것이 맞을 것 같습니다.

오늘 서버 준비해 놓고
이곳에 정보 남기겠습니다. ^^

**Comment by E-nuri** [comment]
@jongkwang 넵, 일단 이 애저 패스는 6개월간 월 $100 리미트로 사용가능하다고합니다.
저는 개인 테스트용(?)으로 사용하려고하니 필요하신분은 메일주셔도 될 것 같습니다.

**Comment by jongkwang** [comment]
iotlabs.net 도메인으로 서버 셋팅하고 있습니다.
셋팅되면 Wiki 를 통해 공유 하겠습니다.
