### ISSUE TITLE
LCD Display 출력 개발

### ISSUE THREAD

**Issue by jongkwang** [iot-labs/farm#28]
## Goal
- 아두이노에 LCD Display 를 연결하고
- "IoT Labs" 문구를 출력한다
- 나중에 이 LCD Display 를 이용하여 온도/습도/조도 값을 표시할 것이다.

## 결과물
- 회로도 (참고 : http://fritzing.org )
- 설명
- 사진
- 문서 위치 : https://github.com/iot-labs/farm/tree/master/Documents/Arduino/Arduino_LCDDisplay.md
- Code 위치 : https://github.com/iot-labs/farm/tree/master/Platforms/Arduino/Arduino_LCDDisplay.ino

**Comment by jongkwang** [comment]
우리 보유한 장비 정보 입니다.
- https://www.aliexpress.com/item/0-91-Inch-128x32-IIC-I2C-Blue-OLED-LCD-Display-DIY-Module-SSD1306-Driver-IC-DC/32793415973.html?spm=a2g0s.9042311.0.0.KalTk7

**Comment by E-nuri** [comment]
Lcd 라이브러리를 적용할 때 주의할 점이 있습니다.
예전에 아두이노를 공부하면서 겪은 문제점 중 하나입니다.

LiquidCrystal_I2C.h 이 라이브러리를 사용할 경우 주의하셔야합니다.

사용자들이 라이브러리를 커스터마이징해서 사용하고 배포하면서 어떤 라이브러리가 정상인지, 비정상인지조차 파악할 수 없을정도가 됐다고 합니다.

그래서 lcd 디스플레이를 위한 라이브러리를 사용하실때는 hd44780이라는 라이브러리를 찾아서 적용하시면 됩니다.

위의 내용은 아두이노 포럼에서 발견한 내용이며 원문은 아래 링크를 참고하시면 됩니다.
https://forum.arduino.cc/index.php?topic=365435.0

**Comment by jongkwang** [comment]
오호~ 감사합니다.!!

메뉴얼에 해당 내용도 적어 놓을께요 ^^

**Comment by jongkwang** [comment]
- LCD Display Library : https://www.dropbox.com/s/i1c4azq9gzkxsmj/ESP8266_Oled_Driver_for_SSD1306_display.zip?dl=0

**Comment by jongkwang** [comment]
Pull Request #43  에서 처리되어 Close 합니다.
수고하셨어요 ^^
