### ISSUE TITLE
Wifi 모듈개발

### ISSUE THREAD

**Issue by ohnewdev** [iot-labs/farm#32]
## Task

* esp8266 mod 에서 node MCU 를 이용한 wifi 연결부 개발
* 센서들의 데이터들의 서버로 전송 및 On/Off 등을 제어하기 위함

**Comment by jongkwang** [comment]
## 참고 자료
- esp8266 기본 설정 : http://www.hardcopyworld.com/gnuboard5/bbs/board.php?bo_table=lecture_esp&wr_id=32
- esp8266 Wifi 설정 : http://www.hardcopyworld.com/gnuboard5/bbs/board.php?bo_table=lecture_esp&wr_id=44

**Comment by jongkwang** [comment]
Port 인식 문제 참고자료 입니다.

- http://blog.naver.com/PostView.nhn?blogId=yulian&logNo=221018644987&parentCategoryNo=&categoryNo=55&viewDate=&isShowPopularPosts=true&from=search

**Comment by jongkwang** [comment]
저는 이것 설치 했었습니다.
https://www.silabs.com/products/development-tools/software/usb-to-uart-bridge-vcp-drivers

**Comment by jongkwang** [comment]
Pull Request #49 #50 에서 처리되어 Close 합니다.
수고하셨어요 ^^
