### ISSUE TITLE
Arduino IDE 에 ESP8266 추가 하기 + 문서작업

### ISSUE THREAD

**Issue by jongkwang** [iot-labs/farm#36]
### Arduino IDE 에 ESP8266 추가 하기

- Arduino IDE 에 추가 방법 : http://www.hardcopyworld.com/gnuboard5/bbs/board.php?bo_table=lecture_esp&wr_id=32
- USB 연결 (USB to UART Bridge VCP Drivers) : https://www.silabs.com/products/development-tools/software/usb-to-uart-bridge-vcp-drivers

### "Arduino IDE 에 ESP8266 추가 하기" 방법을 문서화 한다

- 문서 난이도 : 이 글을 보면 누구나 할 수 있는 수준
- 문서 위치1 : https://github.com/iot-labs/farm/tree/master/Documents/Arduino/SetupArduinoIDE_ESP8266.md
- 문서 위치2 : 위키에 추가

**Comment by jongkwang** [comment]
- 보유중인 장비 정보 : http://eleparts.co.kr/EPXHLDBB

**Comment by DubleDstudy** [comment]
완료했습니다

**Comment by jongkwang** [comment]
Pull Request #42 에서 처리되어 Close 합니다.
수고하셨습니다. ^^
