### ISSUE TITLE
Arduino - 광 선세 개발

### ISSUE THREAD

**Issue by jongkwang** [iot-labs/farm#38]
### Arduino - 광 선세 개발

- 광량 측정

## 문서화

- 문서 수준 : 이 글을 보면 누구나 할 수 있는 수준
- 포함 내용
  - 설명
  - 회로도 : http://fritzing.org 이용
  - Code
- 문서 위치 : https://github.com/iot-labs/farm/tree/master/Documents/Arduino/Arduino_CDSSensor.md
- Code 위치 : https://github.com/iot-labs/farm/tree/master/Platforms/Arduino/Arduino_CDSSensor.ino

**Comment by ssunhj2** [comment]
## 조도센서

### code 

int lightPin = 0;
int threshold = 250;
 
void setup()
{

    Serial.begin(9600);
    pinMode(13, OUTPUT);
}
 
void loop()
{

    Serial.println(analogRead(lightPin)); 
    if(analogRead(lightPin) > threshold ){    
        digitalWrite(13, HIGH);
        Serial.println("high"); 
    }else{
        digitalWrite(13, LOW);
        Serial.println("low"); 
    }
    delay(1000);
}

### 회로도
![image](https://user-images.githubusercontent.com/22341443/32991265-8140e5d0-cd7b-11e7-9951-71d48d8dfcc2.png)

**Comment by ssunhj2** [comment]
## 조도센서 (node mcu 버전)

### 결과

#### 빛 공급받을때 수치
![turnon](https://user-images.githubusercontent.com/22341443/33019470-e235bbb4-ce3d-11e7-8cf1-cc786556abbb.PNG)


#### 빛을 차단했을때 수치
![turnoff](https://user-images.githubusercontent.com/22341443/33019522-0f74818c-ce3e-11e7-849c-f6897f18c2a4.PNG)

### code 

void setup() 
{

	Serial.begin(9600);  // 시리얼 통신을 시작. 속도는 9600 으로 설정
}

void loop() 
{

	int sensorValue = analogRead(A0);  // 아날로그값을 저장

	float voltage = sensorValue * (5.0 / 1023.0);  // 아날로그 값을 변환

	Serial.println(voltage);  // 저장된 값을 출력

        delay(1000);  // 1초 delay

}

### 회로도

![nodemcu](https://user-images.githubusercontent.com/22341443/33019901-90143034-ce3f-11e7-94e0-016241e9ef1a.PNG)

**Comment by jongkwang** [comment]
.md 파일과 .ino 파일을
이곳 말고 해당 위치에 넣어 주세요 ^^
![screen_shot_2017-11-20_at_10_12_31_pm](https://user-images.githubusercontent.com/897510/33020103-4961588c-ce40-11e7-8902-862fa774c01d.png)

**Comment by jongkwang** [comment]
그리고 가급적, 회로도를 이쁘게 그려주세요
선이 너무 꼬였어요~

센서의 위치를 옮기면 점퍼 케이블이 깔끔하게 정리 되겠습니다.

**Comment by jongkwang** [comment]
Pull Request #51 #52  에서 처리되어 Close 합니다.
수고하셨어요 ^^
