### ISSUE TITLE
Arduino 토양 습도 센서 개발 + 문서화

### ISSUE THREAD

**Issue by jongkwang** [iot-labs/farm#39]
### Arduino SDCard Read/Write 개발

- SD Card 읽기가 가능해야 한다
- SD Card 쓰기가 가능해야 한다

## 문서화

- 문서 수준 : 이 글을 보면 누구나 할 수 있는 수준
- 포함 내용
  - 설명
  - 회로도 : http://fritzing.org 이용
  - Code
- 문서 위치 : https://github.com/iot-labs/farm/tree/master/Documents/Arduino/ArduinoSDCard_SoilMoistureSensor.md
- Code 위치 : https://github.com/iot-labs/farm/tree/master/Platforms/Arduino/ArduinoSDCard_SoilMoistureSensor.ino

**Comment by jongkwang** [comment]
보유중인 장비 정보 : http://eleparts.co.kr/EPXFK8XP

**Comment by DubleDstudy** [comment]
해결하고 있습니다.

**Comment by jongkwang** [comment]
Pull Request #46  에서 처리되어 Close 합니다.
수고하셨어요 ^^
