### ISSUE TITLE
The temperature / humidity sensor documentation needs to be modified. - 온도/습도 센서 문서 수정이 필요합니다.

### ISSUE THREAD

**Issue by jongkwang** [iot-labs/farm#57]
@ctk03272 , temperature / humidity sensor document correction is required.

[Edit]
- The title has been repeated twice.
- Markdown of the code part is invalid

----

@ctk03272 님, 온도/습도 센서 문서 수정이 필요합니다.

[수정할 부분]
- 제목이 2번 반복되고 있습니다.
- 코드 부분의 마크다운이 잘못 되었습니다

**Comment by ctk03272** [comment]
제가 수정하도록 하곘습니다.

**Comment by jongkwang** [comment]
It was a simple task, so I went ahead.
The issue is finalized.

----

간단한 작업이라 제가 진행했습니다.
이슈는 완료처리 합니다.
