### ISSUE TITLE
면적이 큰 Farm에서의 센서와 서버간 통신.

### ISSUE THREAD

**Issue by lsahn-gh** [iot-labs/farm#60]
농장이라면 면적이 작거나 크거나 크기가 랜덤할텐데, 서버가 클라우드에 존재하면 어떻게 통신하시는지 궁금하네요.
예를 들면, LoRa, LTE나 아니면 Wireless Local Network로 구성되어 있으신건가요?

**Comment by jongkwang** [comment]
안녕하세요
Issue 감사드립니다. ^^

## 현재 Target

#### 어려움
  - 실제 농장 환경을 조사해 봤는데요
  - Network 를 구성하기 어려운 환경이었습니다
    - 보통 농가와 농장이 수km 떨어진 경우도 있고요.
    - 주변에 아무것도 없어서, 전기가 있는 것 조차 다행인 정도 였습니다

#### 제작 단가 측면 때문에
- LoRa / LTE / 위성통신 부분은 포함되지 않았습니다.

#### 그래서
- SDCard 에 로그를 남기고
- 1년에 한번씩 수거 하는 방향으로 생각 하고 있습니다.
- 그리고, Demo Version 에서는 Wi-Fi 연결을 합니다.

단가 5,000원 미만을 타겟으로 하고 있거든요 ^^

**Comment by lsahn-gh** [comment]
아 그러시군요.
답변 감사합니다.
