### ISSUE TITLE
커밋 메시지 규칙 정하기

### ISSUE THREAD

**Issue by E-nuri** [iot-labs/farm#7]
기능 또는 문서를 **추가**하는 경우
Add '기능/문서의 이름' - '기능/문서 설명'

기능 또는 문서를 **수정**하는 경우
Fix '기능/문서의 이름' - '기능/문서 설명'

위의 예시처럼 커밋 메시지만 보고 어떤 작업을 한건지 파악하기 쉽도록 작성하는 규칙 만드는것을 건의합니다.

참고 자료 : [링크](https://github.com/iot-labs/github-training/blob/master/Github%20Training%20Keynote%20-%201st.pdf)

**Comment by jongkwang** [comment]
좋은 자료가 있어서 첨부 합니다.

- 좋은 git 커밋 메시지를 작성하기 위한 7가지 약속 : http://meetup.toast.com/posts/106
- Git 커밋 메시지 작성법 : https://item4.github.io/2016-11-01/How-to-Write-a-Git-Commit-Message/
- [번역]GitHub / Commits / 커밋 메시지로 이슈 닫기 - http://minsone.github.io/git/github-commits-closing-issues-via-commit-messages

위 2개 링크는 [Wiki](https://github.com/iot-labs/farm/wiki)에도 올려 놓겠습니다

**Comment by ziapapa** [comment]
- github fork 후 원본과 sync 맞추기(cli) : http://fronteer.kr/bbs/view/188
- github fork 에서 pull request 까지 그리고 merge(소스트리) : https://medium.com/axisj/github-fork-%EC%97%90%EC%84%9C-pull-request-%EA%B9%8C%EC%A7%80-%EA%B7%B8%EB%A6%AC%EA%B3%A0-merge-a22bdd097283

**Comment by jongkwang** [comment]
위 내용을 wiki 에 등록 했습니다.
이슈는 Close 처리 합니다.

https://github.com/iot-labs/farm/wiki
