### ISSUE TITLE
컨트리뷰톤 기간 동안 구현할 기능 정의

### ISSUE THREAD

**Issue by E-nuri** [iot-labs/farm#8]
## 현재상황
[초기 회의자료](https://github.com/iot-labs/farm/blob/develop/Documents/Minutes/2017.09.28%20회의록%20-%20컨트리뷰톤%20모임에서%20아이디어%20회의.md)를 보면 구현 할 기능을 정하지 못한채 킥오프 미팅이 끝났습니다.

온도측정, 습도측정, 광량측정, 해당 농장의 온/습도 정보 시각화 등 **기능** 중심으로 목표를 설정한 후 필요부품 조사,, 역할분배, 환경설치 등 후행 작업이 이뤄져야 할 것 같습니다.

코멘트로 구현되면 좋을 기능들을 제안해주세요.

**Comment by ohnewdev** [comment]
1) 현재 저희가 하려는 것이  데이터 수집목적인가요?? (미래 서비스를 위해)
: 시각화도 잘 수집이 되고 있는지에 대한 상태 체크 및 양질의 데이터가 쌓이는지에 대한 연구에 초점인지.... 즉, 잘 자라는 작물을 관찰해서 베이스 데이터를 생성하는 것인지??

2) 아니면,  비록 축적된 베이스 데이터는 없지만 정보수집과 동시에 농부들에게도 동시에 레포팅하여 작물의 상태를 수집하는 것인지요??  
: 1) 내용과 더불어 + 일단 축적된 데이터는 없지만 실시간 또는 1주간격으로 농부들에게 레포팅까지 해주는 것인지요? (최적의 데이터는 없이 일단  온도추이, 습도 추이 등등 )

**Comment by E-nuri** [comment]
https://www.youtube.com/watch?v=O_Q1WKCtWiA&t=463s

킥오프 미팅 끝나고 찾아본 영상입니다.

저희 주제랑 맞는듯한데 보고 의견 부탁드려요.

**Comment by jongkwang** [comment]
@ohnewdev 님,
일단, Data 수집에 1차 목적을 갖도록 하시지요 ^^

저렴하고, 누구나 사용 하기 쉽게 만들어서
**우리나라 모든 농작물의 Data 를 쌓는 것을 목표로 합시다.**

> 대한민국, 농작물 Database 를 구축 하는 것이지요.

**Comment by jongkwang** [comment]
@E-nuri 님,

오호~ 동영상 멋집니다. !!
비슷하다고 볼 수 있네요.

다행인것은
파일 1개 딸랑 있고 아무것도 없네요.
구글링으로 자료를 더 찾아봐도 없구요.

저 친구가 모든걸 만들어서
모든걸 공유 했다면, 우리 프로젝트는 Stop 되었을 텐데요 ^^;;

**Comment by E-nuri** [comment]
@jongkwang 네, 그런데 그 파일 하나에 기능이 다 들어있습니다 ㅠㅠ

DHT22 - 온습도 센서
cds - 광량 감지 센서
vh400 - 토양 습도 감지 센서
therm200 - 토양 온도 감지 센서
FROM HOSE BIB, TO GARDEN - 스텝모터 등을 이용해서 수돗물 공급

저희는 이 기본 내용으로 아두이노 연결하는법, 센서의 신호를 읽어오는법을 공부하고
추가 기능 구현과 센서에서 읽어온 신호를 iotlabs-dashboard를 이용해서 시각화 하는 걸 해보면 어떨까합니다.

**Comment by jongkwang** [comment]
@E-nuri 
헐~ 코드가 고작 200Line 정도 되던데요.
거기에 다 있었다고요?? 우와~~

특히
- 토양온도 감지 센서
- 스텝모터
이렇게는 신선하네요.

많이 참고 합시다. MIT 라이센스에 대한 예의이니까요 ^^

**Comment by E-nuri** [comment]
[contributon.pdf](https://github.com/iot-labs/farm/files/1389932/contributon.pdf)

@jongkwang 우선 위에서 언급됐던 4가지 기능만 우선 구현해보는걸로 하는건 어떨까요?
pdf로 해야할 것들 도식화했는데 코멘트 부탁드립니다.

**Comment by jongkwang** [comment]
@E-nuri 님,
README.md 에 좀 올려주세요 ^^

그리고 안드로이드 시뮬레이터로 먼저 만들어 보는 것이 좋을 것 같습니다.
제가 먼저 한번 만들어 보겠습니다. ^^

**Comment by jongkwang** [comment]
이 이슈는 종료하고
추가 논의는 새로운 이슈 생성 후 진행 하는 것으로 하겠습니다.
