### ISSUE TITLE
Device 선정 (Arduino or Raspberry Pi)

### ISSUE THREAD

**Issue by jongkwang** [iot-labs/farm#9]
# Base 가 될 Device 선정이 필요합니다.

> 이곳에서 논의 하도록 하겠습니다.

## Device

- Arduino
- Raspberry Pi

**Comment by jongkwang** [comment]
## Arduino 장점
- 개발 속도가 빠르다
- 소비 전력이 적다
- Device 가 저렴하다
- SD Card 제어 가능 (별도 모듈 추가)

## Raspbeery Pi 장점
- (동물 감시) 카메라 추가 가능
- Display 연결하여 Web Dashboard 를 현장에서 보여 줄 수 있다.
  - 이 기능은 현장에서 Display 로 보여주기 보다
  - Mobile App 으로 서비스 하는 것이 편리하다

## 김종광 의견
- Arduino 기반으로 개발하고
- 동물 감시 카메라 기능만 Raspberry Pi 로 개발한다

여러분은 어떻게 생각 하세요?
- 댓글 달아 주셔도 좋고
- 손모양 이모티콘이라도 달아주세요.

**Comment by ja-ho** [comment]
전 우선 시작이 중요하다고 생각되서 아두이노로 먼저 기본적인 기능을 구현하는 게 중요할 것 같다고 생각합니다. 카메라 기능 등은 나중에 꼭 구현해보고 싶은 기능이지만 핵심 기능 개발 후로 일단은 미뤄놓는 게 좋을 것 같아요.

**Comment by E-nuri** [comment]
@ja-ho 저도 동의합니다. 처음부터 복잡한 기능을 구현하기보다 쉬운 기능들부터 만들어서 기본적인 기능 구현이 끝난 뒤 복잡한 기능을 구현했으면 합니다.

**Comment by ohnewdev** [comment]
저도 @ja-ho 님과 같은 의견입니다. 
일단 쉽게 시작해서 프로세스를 잘 만들어보면 좋을 것 같습니다.
그 다음 후에 욕심을 내어도 좋겠지요~ㅎ

**Comment by E-nuri** [comment]
@jongkwang 동물 감시 카메라 기능의 경우 영상처리(OpenCV) 작업이 들어가야하는데 OpenCV 라이브러리 익히는데에도 시간이 적지않게 들 것 같습니다. @ja-ho 님 의견처럼 복잡한 기능은 Todo 작업으로 뒀으면 합니다.

**Comment by jongkwang** [comment]
동감입니다.!!

작은것 부터 먼저 진행 하시지요. ^^

**Comment by jongkwang** [comment]
의견을 종합하여
두이노로 결정 하고 진행 하는 것으로 하겠습니다.

추가 보드가 필요하면,
별도의 이슈를 생성해서 진행 하도록 하시지요 ^^
